semi: true
tabWidth: 2
useTabs: false
printWidth: 100
singleQuote: true
bracketSpacing: true
jsxSingleQuote: false
jsxBracketSameLine: false
trailingComma: es5
arrowParens: avoid
endOfLine: lf
parser: babel
